### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by gfredericks** [palletops/lein-shorthand#9]
Issues and PRs in this repo have not been responded to in over two years.

I'm an active user, and would be happy to take over maintenance if somebody can give me permissions to the repo and clojars.

**Comment by gfredericks** [comment]
½ in lieu of getting a response to this, I've started [dot-slash-2](https://github.com/gfredericks/dot-slash-2), which is like lein-shorthand but is a library instead of a lein plugin.

**Comment by hugoduncan** [comment]
@gfredericks I have given you full admin access to this.  Feel free to deprecate and point to your lib, if that is your preferred solution.

**Comment by gfredericks** [comment]
@hugoduncan thanks!

It looks like clojars only has group-level permissions, so I'd have to be added to all of `com.palletops` to be able to do a release.

I don't feel any need to deprecate lein-shorthand, since aside from #6 I think it works fine and for now has more features than https://github.com/gfredericks/dot-slash-2.

I definitely want to make a release after merging #6 though. So I think I will merge it and wait a week to see if you either add me to the clojars group or perform a release yourself. If neither of those happen, I will start releasing it under `com.gfredericks/lein-shorthand`.
